<a href="https://colab.research.google.com/github/lpacheco560/Curso-Inteligencia-Artificial/blob/main/EDA_Apuntes_de_Clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#EDA Analisis Exploratorios
**Ejemplos**

Importar librerias


In [9]:
!pip list


Package                            Version
---------------------------------- -------------------
absl-py                            1.4.0
accelerate                         1.3.0
aiohappyeyeballs                   2.4.6
aiohttp                            3.11.12
aiosignal                          1.3.2
alabaster                          1.0.0
albucore                           0.0.23
albumentations                     2.0.4
ale-py                             0.10.1
altair                             5.5.0
annotated-types                    0.7.0
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.6.0
arviz                              0.20.0
astropy                            7.0.1
astropy-iers-data                  0.2025.2.10.0.33.26
astunparse                         1.6.3
atpublic                           4.1.0
attrs                              25.1.0
audioread          

In [10]:
!ls -la


total 16
drwxr-xr-x 1 root root 4096 Feb 18 14:20 .
drwxr-xr-x 1 root root 4096 Feb 19 21:25 ..
drwxr-xr-x 4 root root 4096 Feb 18 14:19 .config
drwxr-xr-x 1 root root 4096 Feb 18 14:20 sample_data


In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df=pd.read_csv('https://raw.githubusercontent.com/adiacla/bigdata/refs/heads/master/vivienda_clasif.csv")
df.head()

SyntaxError: unterminated string literal (detected at line 1) (<ipython-input-12-f636b65a6bd0>, line 1)

https://raw.githubusercontent.com/adiacla/bigdata/refs/heads/master/vivienda_clasif.csv

Con el sigiente veo los 10 primeros registros

In [23]:
df.head(10)


NameError: name 'df' is not defined

Con este comando veo los ultimos datos

In [22]:
df.tail()

NameError: name 'df' is not defined

In [21]:
df.local=pd.read_csv("vivienda_clasif.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'vivienda_clasif.csv'

In [20]:
df

NameError: name 'df' is not defined

In [19]:
df_github=pd.read_csv("https://raw.githubusercontent.com/lpacheco560/Curso-Inteligencia-Artificial/refs/heads/main/preprocesamiento/vivienda_clasif.csv")
df

NameError: name 'df' is not defined

In [18]:
df.shape

NameError: name 'df' is not defined

In [17]:
df

NameError: name 'df' is not defined

In [16]:
import numpy as np

# Set random seed
np.random.seed(42)

# Create 'saldo' array with synthetic bank balance data
saldo = np.random.randint(1000, 10000, size=20)  # Random balances between 1000 and 10000

# Create 'antiguedad' array for bank account age
antiguedad = np.arange(0, 10, 0.5)  # Values from 0 to 10 with a step of 0.5

# Create 'ubicacion' matrix with latitude and longitude near Bucaramanga
latitud = 7.12 + np.random.rand(20) * 0.1  # Vary latitude around 7.12
longitud = -73.12 + np.random.rand(20) * 0.1  # Vary longitude around -73.12
ubicacion = np.column_stack((latitud, longitud))

# Combine using column_stack
datos_combinados = np.column_stack((saldo, antiguedad, ubicacion))

print(datos_combinados)

[[ 8.27000000e+03  0.00000000e+00  7.17247564e+00 -7.31102328e+01]
 [ 1.86000000e+03  5.00000000e-01  7.16319450e+00 -7.30515767e+01]
 [ 6.39000000e+03  1.00000000e+00  7.14912291e+00 -7.30759848e+01]
 [ 6.19100000e+03  1.50000000e+00  7.18118529e+00 -7.31077962e+01]
 [ 6.73400000e+03  2.00000000e+00  7.13394939e+00 -7.30704823e+01]
 [ 7.26500000e+03  2.50000000e+00  7.14921446e+00 -7.31165611e+01]
 [ 1.46600000e+03  3.00000000e+00  7.15663618e+00 -7.30290680e+01]
 [ 5.42600000e+03  3.50000000e+00  7.16560700e+00 -7.30941220e+01]
 [ 6.57800000e+03  4.00000000e+00  7.19851760e+00 -7.30537478e+01]
 [ 9.32200000e+03  4.50000000e+00  7.13996738e+00 -7.30888289e+01]
 [ 2.68500000e+03  5.00000000e+00  7.17142344e+00 -7.30679932e+01]
 [ 1.76900000e+03  5.50000000e+00  7.17924146e+00 -7.30653290e+01]
 [ 7.94900000e+03  6.00000000e+00  7.12464504e+00 -7.31015146e+01]
 [ 3.43300000e+03  6.50000000e+00  7.18075449e+00 -7.30230415e+01]
 [ 6.31100000e+03  7.00000000e+00  7.13705241e+00 -7.30424867e

In [15]:
datos_combinados.shape

(20, 4)

In [14]:
print("media",np.mean(datos_combinados[0]),"\n","max",np.max(datos_combinados[0]),"\n","min",np.min(datos_combinados[0]))

media 2051.0155607136408 
 max 8270.0 
 min -73.11023278859936


In [13]:
datos_combinados[:,:] # exactamente igual a datos_combinados

array([[ 8.27000000e+03,  0.00000000e+00,  7.17247564e+00,
        -7.31102328e+01],
       [ 1.86000000e+03,  5.00000000e-01,  7.16319450e+00,
        -7.30515767e+01],
       [ 6.39000000e+03,  1.00000000e+00,  7.14912291e+00,
        -7.30759848e+01],
       [ 6.19100000e+03,  1.50000000e+00,  7.18118529e+00,
        -7.31077962e+01],
       [ 6.73400000e+03,  2.00000000e+00,  7.13394939e+00,
        -7.30704823e+01],
       [ 7.26500000e+03,  2.50000000e+00,  7.14921446e+00,
        -7.31165611e+01],
       [ 1.46600000e+03,  3.00000000e+00,  7.15663618e+00,
        -7.30290680e+01],
       [ 5.42600000e+03,  3.50000000e+00,  7.16560700e+00,
        -7.30941220e+01],
       [ 6.57800000e+03,  4.00000000e+00,  7.19851760e+00,
        -7.30537478e+01],
       [ 9.32200000e+03,  4.50000000e+00,  7.13996738e+00,
        -7.30888289e+01],
       [ 2.68500000e+03,  5.00000000e+00,  7.17142344e+00,
        -7.30679932e+01],
       [ 1.76900000e+03,  5.50000000e+00,  7.17924146e+00,
      

Como mostrar datos con ubicación negativa, la matriz es de 20 líneas, las filas son la X y las columnas Y

In [26]:
datos_combinados[-5:-2,1:3]

array([[7.5       , 7.12650516],
       [8.        , 7.21488855],
       [8.5       , 7.2165632 ]])

In [29]:
# prompt: creame una lista de 20 nombres colombianos en un arreglo de numpy que se llaman nombre

import numpy as np

nombres = np.array(['Juan', 'Ana', 'Carlos', 'Sofia', 'David', 'Maria', 'Jose', 'Laura', 'Miguel', 'Valentina',
                   'Sebastian', 'Camila', 'Alejandro', 'Isabella', 'Daniel', 'Gabriela', 'Nicolas', 'Sofia', 'Mateo', 'Andrea'])



In [30]:
nombres

array(['Juan', 'Ana', 'Carlos', 'Sofia', 'David', 'Maria', 'Jose',
       'Laura', 'Miguel', 'Valentina', 'Sebastian', 'Camila', 'Alejandro',
       'Isabella', 'Daniel', 'Gabriela', 'Nicolas', 'Sofia', 'Mateo',
       'Andrea'], dtype='<U9')

In [ ]:
n

In [31]:
# prompt: crea un dataframe que una nombre, saldos, atiguedad, latitud, longitud

import pandas as pd
import numpy as np

# Assuming 'nombres', 'saldo', 'antiguedad', 'latitud', and 'longitud' are defined as in the previous code

# Create a DataFrame
data = {'nombre': nombres,
        'saldo': saldo,
        'antiguedad': antiguedad,
        'latitud': latitud,
        'longitud': longitud}
df = pd.DataFrame(data)

df


nombre  saldo  antiguedad   latitud   longitud
0        Juan   8270         0.0  7.172476 -73.110233
1         Ana   1860         0.5  7.163195 -73.051577
2      Carlos   6390         1.0  7.149123 -73.075985
3       Sofia   6191         1.5  7.181185 -73.107796
4       David   6734         2.0  7.133949 -73.070482
5       Maria   7265         2.5  7.149214 -73.116561
6        Jose   1466         3.0  7.156636 -73.029068
7       Laura   5426         3.5  7.165607 -73.094122
8      Miguel   6578         4.0  7.198518 -73.053748
9   Valentina   9322         4.5  7.139967 -73.088829
10  Sebastian   2685         5.0  7.171423 -73.067993
11     Camila   1769         5.5  7.179241 -73.065329
12  Alejandro   7949         6.0  7.124645 -73.101515
13   Isabella   3433         6.5  7.180754 -73.023042
14     Daniel   6311         7.0  7.137052 -73.042487
15   Gabriela   6051         7.5  7.126505 -73.026050
16    Nicolas   7420         8.0  7.214889 -73.030517
17      Sofia   2184         8.5  7.216563 -73.060210
18      Mateo   5555         9.0  7.200840 -73.027813
19     Andrea   4385         9.5  7.150461 -73.111151

from matplotlib import pyplot as plt
df['saldo'].plot(kind='hist', bins=20, title='saldo')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['antiguedad'].plot(kind='hist', bins=20, title='antiguedad')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['latitud'].plot(kind='hist', bins=20, title='latitud')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['longitud'].plot(kind='hist', bins=20, title='longitud')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='saldo', y='antiguedad', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='antiguedad', y='latitud', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='latitud', y='longitud', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['antiguedad']
  ys = series['saldo']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('antiguedad', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('antiguedad')
_ = plt.ylabel('saldo')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['antiguedad']
  ys = series['latitud']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('antiguedad', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('antiguedad')
_ = plt.ylabel('latitud')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['antiguedad']
  ys = series['longitud']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('antiguedad', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('antiguedad')
_ = plt.ylabel('longitud')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['antiguedad']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'antiguedad'}, axis=1)
              .sort_values('antiguedad', ascending=True))
  xs = counted['antiguedad']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('antiguedad', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('antiguedad')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
df['saldo'].plot(kind='line', figsize=(8, 4), title='saldo')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['antiguedad'].plot(kind='line', figsize=(8, 4), title='antiguedad')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['latitud'].plot(kind='line', figsize=(8, 4), title='latitud')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['longitud'].plot(kind='line', figsize=(8, 4), title='longitud')
plt.gca().spines[['top', 'right']].set_visible(False)

In [33]:
df.to_excel("datos.xlsx")